#!/usr/bin/env php
<?php
// application.php

//require __DIR__ . '/../../vendor/autoload.php';
require __DIR__ . '/../../../vendor/autoload.php';

use Symfony\Component\Console\Application;
use CodeCommerce\ModuleSkeleton\Command\CreateStructurCommand;

$application = new Application();
// ... register commands
$application->add(new CreateStructurCommand());

$application->run();

