parameters:
  basepath: ../../../
  modulebasepath: source/modules/
  composer_update: false

vendor:
  moduleskeleton:
    namespace: moduleskeleton
    homepage: https://www.musdertomain.de
    email: info@musdertomain.de

authors:
  Max:
    name: Max Mustermann
    email: max@mustermann.de
    homepage: https://www.musdertomain.de

filestructur:
  generate_directories: true
  directories:
    - "Core/Events"
    - "Controller/Admin"
    - "Model"
    - "out/src/css"
    - "out/src/img"
    - "out/src/js"
    - "setup"
    - "translations/de"
    - "views/admin/de"
    - "views/admin/tpl"
    - "views/blocks"
  generate_files: true
  files:
    - "setup/install.sql"

metadata:
  thumbnail: 'logo.jpg'
  modul_version: '1.0'
  metadata_version: '2.1'

template_files:
  type: path
  path: "Config/Templates" # path to files
